### ISSUE TITLE
Banco de dados

### ISSUE THREAD

**Issue by jpfs2001** [bmarchete/tic-tac-toe-php#1]
Olá professor, você não adicionou o banco de dados do projeto para nós testarmos o jogo e tentarmos fazer em casa.

Espero que resolva rápido, Obrigado. 👍

**Comment by MarrentaxD** [comment]
Por favor, nós alunos agradecemos! :smile: :top: :ear:

**Comment by bmarchete** [comment]
Gostei de ver o uso de issues, parabéns!

Já inseri o banco de dados! 👌
